### ISSUE TITLE
No generators appear on app start

### ISSUE THREAD

**Issue by techmsi** [yeoman/yeoman-app#93]
On node **v4.2.2 (npm v2.14.7)**, I run `npm start`, electron app loads, a list of my installed generators is logged to the console but nothing appears in the window. 
```
{ name: 'generator-angular',
       version: '0.14.0',
       description: 'Yeoman generator for AngularJS',
       isCompatible: false,
       officialGenerator: false },
     { name: 'generator-chrome-extension',
       version: '0.4.4',
       description: 'Scaffold out a Chrome extension',
       isCompatible: true,
       officialGenerator: false },
```
The html appears empty:

```html
<main id="content"></main>
```
<img width="249" alt="empty2015-12-10" src="https://cloud.githubusercontent.com/assets/1686333/11717122/666fd6ba-9f1c-11e5-8505-353e7a60fee4.png">

**Comment by stefanbuck** [comment]
Hi @techmsi, 

thanks for reporting. This issue is affected by the `material-ui` changes see https://github.com/yeoman/yeoman-app/pull/90. @ruyadorno is already on it.

If you like, checkout @ruyadorno fix branch https://github.com/ruyadorno/yeoman-app/tree/update-material-ui-fix-88 in the meantime.
